#!/usr/bin/env python3
"""Generate references/tool-catalog.md from references/tool-catalog.json.

This is the single direction: JSON is canonical; MD is a generated view.
Never hand-edit the markdown output.

Usage:
    python scripts/build_catalog_md.py [--json PATH] [--out PATH]
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_ROOT = SCRIPT_DIR.parent
DEFAULT_JSON = SKILL_ROOT / "references" / "tool-catalog.json"
DEFAULT_OUT = SKILL_ROOT / "references" / "tool-catalog.md"

CATEGORY_META = {
    "web-scraper":     {"icon": "🕸️", "title": "静态网页抓取"},
    "dynamic-scraper": {"icon": "⚡", "title": "动态页面抓取"},
    "api-collector":   {"icon": "🔌", "title": "API 数据采集"},
    "agent-skill":     {"icon": "🤖", "title": "Agent 技能 / MCP"},
    "dataset":         {"icon": "📚", "title": "数据集 / 资源库"},
}

# Chinese social platform groups — order matters for the aggregation block.
# Each platform: (key, display_name). Sub-tags on entries: platform:<key>.
CHINESE_SOCIAL_GROUPS = [
    ("主流七大", [
        ("xiaohongshu", "小红书"),
        ("douyin", "抖音"),
        ("bilibili", "哔哩哔哩"),
        ("weibo", "微博"),
        ("zhihu", "知乎"),
        ("tieba", "百度贴吧"),
        ("kuaishou", "快手"),
    ]),
    ("微信生态", [
        ("wechat-oa", "微信公众号"),
        ("wechat-channels", "视频号"),
        ("wechat-search", "微信搜一搜"),
    ]),
    ("电商评论", [
        ("taobao", "淘宝/天猫"),
        ("jd", "京东"),
        ("pdd", "拼多多"),
    ]),
    ("垂直社区", [
        ("douban", "豆瓣"),
        ("jike", "即刻"),
        ("xueqiu", "雪球"),
        ("juejin", "掘金"),
        ("v2ex", "V2EX"),
        ("xianyu", "闲鱼/得物"),
    ]),
]


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--json", type=Path, default=DEFAULT_JSON)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()

    doc = json.loads(args.json.read_text(encoding="utf-8"))
    entries = doc.get("entries", [])
    last_refreshed = doc.get("last_refreshed", "")

    by_cat: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        by_cat[e.get("category", "dataset")].append(e)
    for cat in by_cat:
        by_cat[cat].sort(key=lambda e: -e.get("stars", 0))

    total = len(entries)
    verified = sum(1 for e in entries if e.get("verified"))
    favorite = sum(1 for e in entries if e.get("favorite"))

    out: list[str] = []
    out.append("<!-- AUTO-GENERATED by scripts/build_catalog_md.py — do not edit. "
               "Edit references/tool-catalog.json and re-run. -->\n")
    out.append("# Tool Catalog\n")
    out.append(f"- **Last refreshed:** {last_refreshed}\n")
    out.append(f"- **Total entries:** {total}  |  **Verified:** {verified}  |  "
               f"**Favorite:** {favorite}\n")
    out.append("- **Canonical source:** `references/tool-catalog.json`\n\n")

    # --- Summary table ---
    out.append("## Summary\n\n")
    out.append("| 类别 | 数量 | 已验证 | 平均 star | 最近更新 |\n")
    out.append("|------|------|--------|-----------|----------|\n")
    for cat, meta in CATEGORY_META.items():
        items = by_cat.get(cat, [])
        if not items:
            out.append(f"| {meta['icon']} {meta['title']} (`{cat}`) | 0 | 0 | — | — |\n")
            continue
        avg = sum(e.get("stars", 0) for e in items) // len(items)
        verified_cat = sum(1 for e in items if e.get("verified"))
        recent = max((e.get("last_updated", "") for e in items), default="—")
        out.append(f"| {meta['icon']} {meta['title']} (`{cat}`) | {len(items)} | "
                   f"{verified_cat} | ⭐ {avg:,} | {recent} |\n")
    out.append("\n")

    # --- Chinese social aggregation block ---
    out.extend(_render_chinese_social_block(entries))

    # --- Per-category sections ---
    for cat, meta in CATEGORY_META.items():
        items = by_cat.get(cat, [])
        out.append(f"\n## {meta['icon']} {meta['title']} (`{cat}`)\n\n")
        if not items:
            out.append("_No entries yet. Run `/collection-skill discover` to find some._\n")
            continue
        for e in items:
            out.append(_render_card(e))
            out.append("\n")

    args.out.write_text("".join(out), encoding="utf-8")
    print(f"Wrote {args.out} ({total} entries across {len(by_cat)} categories)")
    return 0


def _render_card(e: dict) -> str:
    stars = e.get("stars", 0)
    last = e.get("last_updated", "—")
    verified = " ✓" if e.get("verified") else ""
    fav = " ⭐" if e.get("favorite") else ""
    desc = e.get("one_line_description") or "_no description_"
    use_cases = e.get("use_cases", []) or []
    caveats = e.get("caveats", []) or []
    tags = e.get("tags", []) or []
    topics = e.get("topics", []) or []
    license_ = e.get("license") or "—"
    lang = e.get("language") or "—"
    notes = e.get("notes") or ""

    lines: list[str] = []
    lines.append(f"### 🔧 {e.get('name', '?')}  ⭐{stars:,}  {last}{verified}{fav}\n")
    lines.append(f"{desc}\n\n")
    if use_cases:
        lines.append("✅ **适合：** " + " · ".join(use_cases) + "\n")
    if caveats:
        lines.append("⚠️ **注意：** " + " · ".join(caveats) + "\n")
    meta_bits = [f"`lang: {lang}`", f"`license: {license_}`"]
    if topics:
        meta_bits.append("topics: " + " ".join(f"`{t}`" for t in topics[:6]))
    lines.append("🏷️  " + " · ".join(meta_bits) + "\n")
    if tags:
        lines.append("🏷️  tags: " + " ".join(f"`#{t}`" for t in tags) + "\n")
    lines.append(f"🔗 {e.get('repo_url', '')}\n")
    if notes:
        lines.append(f"📝 _{notes}_\n")
    return "\n".join(lines) + "\n"


def _entry_platform(e: dict) -> str | None:
    """Extract `platform:xxx` sub-tag from an entry's tags, or None."""
    for t in e.get("tags", []) or []:
        if isinstance(t, str) and t.startswith("platform:"):
            return t.split(":", 1)[1]
    return None


def _render_chinese_social_block(entries: list[dict]) -> list[str]:
    """Render the 🇨🇳 aggregation block, grouped by platform group."""
    out: list[str] = []
    # collect chinese-social entries
    cs_entries = [e for e in entries if "chinese-social" in (e.get("tags") or [])]
    if not cs_entries:
        return out  # no block at all if no chinese-social entries

    # bucket by platform key
    by_platform: dict[str, list[dict]] = {}
    multi_platform_entries: list[dict] = []  # ones covering many platforms (e.g. MediaCrawler)
    for e in cs_entries:
        plat = _entry_platform(e)
        if plat == "multi" or plat is None:
            multi_platform_entries.append(e)
        else:
            by_platform.setdefault(plat, []).append(e)

    out.append("\n## 🇨🇳 中文社交媒体采集 (tag: `chinese-social`)\n\n")
    out.append(f"_{len(cs_entries)} 个工具_  ·  "
               "查看 `references/chinese-social-platforms.md` 获取平台关键词完整映射\n\n")

    # coverage table
    out.append("**平台覆盖：**\n\n")
    out.append("| 平台群 | 平台 | 工具数 | 多平台覆盖 |\n")
    out.append("|--------|------|--------|------------|\n")
    total_tools = 0
    for group_name, platforms in CHINESE_SOCIAL_GROUPS:
        for key, display in platforms:
            n = len(by_platform.get(key, []))
            total_tools += n
            emoji = "✅" if n > 0 else "—"
            out.append(f"| {group_name} | {display} (`{key}`) | {emoji} {n} | "
                       f"{'✓ 见下方' if multi_platform_entries else '—'} |\n")
    out.append("\n")

    # multi-platform umbrella tools first
    if multi_platform_entries:
        out.append(f"\n### 🌐 多平台一体化（{len(multi_platform_entries)}）\n")
        multi_platform_entries.sort(key=lambda e: -e.get("stars", 0))
        for e in multi_platform_entries:
            out.append(_render_card(e))

    # per group, per platform
    for group_name, platforms in CHINESE_SOCIAL_GROUPS:
        group_has_any = any(by_platform.get(key) for key, _ in platforms)
        if not group_has_any:
            continue
        out.append(f"\n### {group_name}\n")
        for key, display in platforms:
            items = by_platform.get(key, [])
            if not items:
                continue
            items.sort(key=lambda e: -e.get("stars", 0))
            out.append(f"\n#### {display} (`platform:{key}`) — {len(items)} 个工具\n")
            for e in items:
                out.append(_render_card(e))

    out.append("\n---\n")
    return out


if __name__ == "__main__":
    raise SystemExit(main())
