#!/usr/bin/env python3
"""Build a weekly "what's new" digest from tool-catalog.json.

The catalog auto-refreshes weekly (see .github/workflows/discover.yml). To give
watchers a reason to subscribe — and to surface the freshness that static
awesome-lists lack — we publish a GitHub Release listing the tools *newly
discovered* in the last N days. Freshness is keyed off each entry's
`discovered_at` (the first time the scanner saw the repo), so re-discovered
entries do not reappear in every digest.

Usage:
    python scripts/make_digest.py [--days 7] [--out digest.md] [--json PATH]

When --out is given, only `count=N` is printed to stdout (so a caller can skip
release creation on a quiet week); otherwise the markdown goes to stdout and
`count=N` to stderr. Exit code is always 0 — a quiet week is not an error.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date, timedelta
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_ROOT = SCRIPT_DIR.parent
DEFAULT_JSON = SKILL_ROOT / "references" / "tool-catalog.json"

CAT_EMOJI = {
    "web-scraper": "🕸️",
    "dynamic-scraper": "⚡",
    "api-collector": "🔌",
    "agent-skill": "🤖",
    "dataset": "📚",
}


def load_new_entries(doc: dict, since: date) -> list[dict]:
    """Entries whose `discovered_at` falls on/after `since`, newest + biggest first."""
    out: list[dict] = []
    for e in doc.get("entries", []):
        raw = (e.get("discovered_at") or "")[:10]
        try:
            seen = date.fromisoformat(raw)
        except ValueError:
            continue
        if seen >= since:
            out.append(e)
    out.sort(key=lambda e: ((e.get("discovered_at") or ""), e.get("stars", 0)), reverse=True)
    return out


def _cell(text: object) -> str:
    """Make a value safe for a markdown table cell."""
    return str(text or "").replace("|", "\\|").replace("\n", " ").strip()


def render(doc: dict, new: list[dict], since: date, today: date) -> str:
    total = len(doc.get("entries", []))
    lines = [
        f"## 📦 Weekly catalog digest — {since.isoformat()} → {today.isoformat()}",
        "",
        f"**{len(new)}** new tool(s) cataloged this week. The catalog now tracks **{total}**.",
        "",
    ]
    if new:
        lines += [
            "| Tool | Category | ★ | What it does |",
            "|------|----------|--:|--------------|",
        ]
        for e in new:
            cat = e.get("category", "")
            emoji = CAT_EMOJI.get(cat, "")
            lines.append(
                f"| [{_cell(e.get('full_name'))}]({e.get('repo_url', '')}) "
                f"| {emoji} {cat} | {e.get('stars', 0)} | {_cell(e.get('one_line_description'))} |"
            )
        lines.append("")
    lines += [
        "---",
        "_Auto-generated by the weekly discovery run. Browse the full catalog in the "
        "[README](README.md) · [tool-catalog.md](references/tool-catalog.md). "
        "Know a tool that's missing? [Submit it](../../issues/new?template=submit-tool.yml)._",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    # The digest is full of emoji/CJK; don't let a non-UTF-8 console (e.g. a
    # Windows GBK codepage) crash the stdout path.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--days", type=int, default=7, help="Look-back window for 'newly discovered'")
    p.add_argument("--out", type=Path, default=None, help="Write markdown here (default: stdout)")
    p.add_argument("--json", type=Path, default=DEFAULT_JSON)
    args = p.parse_args()

    doc = json.loads(args.json.read_text(encoding="utf-8"))
    today = date.today()
    since = today - timedelta(days=args.days)
    new = load_new_entries(doc, since)
    body = render(doc, new, since, today)

    if args.out:
        args.out.write_text(body, encoding="utf-8")
        print(f"count={len(new)}")
    else:
        print(body)
        print(f"count={len(new)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
